"""Add appointments table

Revision ID: cf5cf7f8a154
Revises: 
Create Date: 2024-05-29 20:08:35.791971

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cf5cf7f8a154'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('availability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('day', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('start_time', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('end_time', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('recurrence', sa.VARCHAR(length=50), nullable=False),
                    sa.Column('barber_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['barber_id'], ['barber.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('booking',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
                    sa.Column('start', sa.VARCHAR(length=100), nullable=False),
                    sa.Column('end', sa.VARCHAR(length=100), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
